# Generated by Django 4.2.1 on 2023-05-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendshiprequest',
            name='status',
            field=models.CharField(blank=True, choices=[('sent', 'Заявка отправлена'), ('rejected', 'Заявка отклонена')], default='sent', max_length=150, verbose_name='Статус заявки'),
        ),
    ]
